swagger: "2.0"
info:
  description: "API for tupperdate"
  version: "1.0.0"
  title: "Tupperdate API"
host: "api.tupperdate.me"
basePath: "/"
schemes:
- "http"

tags:
- name: "users"
  description: "Everything about users"

- name: "recipes"
  description: "Everything about recipes"

paths:
  /users:
    post:
      tags:
      - "users"
      summary: "Post a new user"
      description: ""
      operationId: "postNewUser"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User object that needs to be registered"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "405":
          description: "Invalid input"

  /users/{userId}:
    get:
      tags:
      - "users"
      summary: "Get a user by id"
      description: ""
      operationId: "getUserById"
      produces:
      - "application/json"
      parameters:
      - name: "userId"
        in: "path"
        description: "ID of user"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "User not found"
          
  /recipes:
    post:
      tags:
      - "recipes"
      summary: "Post a recipe for an authenticated user"
      description: ""
      operationId: "postRecipe"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Recipe object that needs to be registered for the authenticated user"
        required: true
        schema:
          $ref: "#/definitions/Recipe"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Recipe"
        "405":
          description: "Invalid input"

  /recipes/next:
    get:
      tags:
      - "recipes"
      summary: "Get a random recipe"
      description: ""
      operationId: "getRandomRecipe"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Recipe"
            
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "string"
      displayName:
        type: "string"
      phone:
        type: "string"
      profilePictureUrl:
        type: "string"
      recipes:
        $ref: "#/definitions/Recipe"
    xml:
      name: "User"

  Recipe:
    type: "object"
    properties:
      id:
        type: "string"
      title:
        type: "string"
      description:
        type: "string"
      foodPictureUrl:
        type: "string"
      attributes:
        type: "string"
    xml:
      name: "Recipe"
