name: Build and publish Android app to Telegram

on:
  push:
    branches: [ dev ]

jobs:
  build:
    name: Build mobile client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [ mock, api ]
        include:
        - variant: mock
          gradle_task: assembleMock

        - variant: api
          gradle_task: assembleApi

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Load secret files
        run: echo "$SIGNING_PROPERTIES_PROD" > ./mobile/signing.properties.prod
        shell: bash
        env:
          SIGNING_PROPERTIES_PROD: ${{ secrets.SIGNING_PROPERTIES_PROD }}

      - name: Build app
        run: ./gradlew ${{ matrix.gradle_task }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-${{ matrix.variant }}
          path: src/mobile/build/outputs/apk/${{ matrix.variant }}/debug/

  test:
    name: Test mobile client
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [ mock, api ]
        include:
        - variant: mock
          gradle_task: testMockDebugUnitTest

        - variant: api
          gradle_task: testApiDebugUnitTest

    defaults:
      run:
        working-directory: src

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Load secret files
        run: echo "$SIGNING_PROPERTIES_PROD" > ./mobile/signing.properties.prod
        shell: bash
        env:
          SIGNING_PROPERTIES_PROD: ${{ secrets.SIGNING_PROPERTIES_PROD }}

      - name: Build app
        run: ./gradlew ${{ matrix.gradle_task }}

  deploy:
    name: Deploy
    needs: [ build, test ]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        variant: [ mock, api ]

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: apk-${{ matrix.variant }}
          path: .


      - name: Push to Telegram
        run: |
          export VERSION_CODE=$(cat output-metadata.json | jq '.elements[0].versionCode')
          export VERSION_NAME=$(cat output-metadata.json | jq '.elements[0].versionName')
          export VARIANT_NAME=$(cat output-metadata.json | jq '.variantName')

          curl -X POST \
            --form-string chat_id=${{ secrets.DEPLOY_TELEGRAM_GROUP }} \
            --form-string caption="âœ… New apk for Tupperdate $VERSION_NAME ($VERSION_CODE) - $VARIANT_NAME" \
            -F document=@mobile-${{ matrix.variant }}-debug.apk \
            https://api.telegram.org/bot${{ secrets.DEPLOY_TELEGRAM_TOKEN }}/sendDocument
