name: Build and publish Android app to Telegram

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8
    
      - name: Build app
        run: |
          cd ./src
          ./gradlew mobile:assemble
      
      - name: Push to Telegram
        run: |
          cp src/mobile/build/outputs/apk/debug/* .
          export VERSION_CODE=$(cat output-metadata.json | jq '.elements[0].versionCode')
          export VERSION_NAME=$(cat output-metadata.json | jq '.elements[0].versionName')

          curl -X POST \
            --form-string chat_id=${{ secrets.DEPLOY_TELEGRAM_GROUP }} \
            --form-string caption="âœ… New apk for Tupperdate $VERSION_NAME ($VERSION_CODE)" \
            -F document=@mobile-debug.apk \
            https://api.telegram.org/bot${{ secrets.DEPLOY_TELEGRAM_TOKEN }}/sendDocument
