name: Update timetracking information
on:
    workflow_dispatch:

    schedule:
      - cron: '0 0 * * 2,5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

      - name: Update time tracking
        run: python3 vcs/timetracking/updateTimeTrack.py >> README.md
        env:
          CLOCKIFY_API_KEY: ${{ secrets.CLOCKIFY_API_KEY }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update time tracking informations
          commit_user_name: Your friendly Bot
          commit_author: Your friendly Bot <actions@github.com>
          push_options: --force
