name: Build and publish Docker image

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Load secret files
        run: |
          echo "$SIGNING_PROPERTIES_PROD" > ./src/mobile/signing.properties.prod
        shell: bash
        env:
          SIGNING_PROPERTIES_PROD: ${{ secrets.SIGNING_PROPERTIES_PROD }}

      - name: Build and publish Docker image
        run: |
          cd ./docker
          sh ./build-image.sh
          sh ./publish-image-github.sh
          sh ./publish-image-heroku.sh
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          TOKEN_HEROKU: ${{ secrets.TOKEN_HEROKU }}

      - name: Release to Heroku
        run: |
          heroku container:login
          heroku container:release -a heig-pdg web
        env:
          HEROKU_API_KEY: ${{ secrets.TOKEN_HEROKU }}

      - name: Notify on Telegram
        run: |
          curl -X POST \
            --form-string chat_id=${{ secrets.DEPLOY_TELEGRAM_GROUP }} \
            --form-string text="âœ… New backend on api.tupperdate.me" \
            https://api.telegram.org/bot${{ secrets.DEPLOY_TELEGRAM_TOKEN }}/sendMessage
